
services:
  db-mysql:
    image: mysql:8.0.33
    restart: always
    environment:
      - MYSQL_DATABASE=kiong_nguyen
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

      